name: PR check
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Run test ${{ matrix.name }}
    runs-on: ubuntu-latest
    services:
      devnet:
        image: shardlabs/starknet-devnet:0.4.2-seed0
        ports:
          - 5050:5050

    strategy:
      max-parallel: 1 # needed until we get a seperate account for the rpc provider, until then running them in parallel would result in a nonce issue
      matrix:
        name: [sequencer-devnet, rpc-devnet]
        include:
          - name: sequencer-devnet
            TEST_PROVIDER_BASE_URL: http://127.0.0.1:5050/
          - name: rpc-devnet
            TEST_RPC_URL: http://127.0.0.1:5050/rpc
    env:
      TEST_PROVIDER_BASE_URL: ${{ matrix.TEST_PROVIDER_BASE_URL }}
      TEST_RPC_URL: ${{ matrix.TEST_RPC_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm test
